apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-dev-apps
  namespace: testappli
rules:
- apiGroups: [""]
  resources: ["configmaps","secrets","services","serviceaccounts","persistentvolumeclaims"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets","deployments","replicasets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-dev-apps
  namespace: testappli
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-dev-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gov-quotas
  namespace: testappli
rules:
- apiGroups: [""]
  resources: ["resourcequotas","limitranges"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gov-quotas
  namespace: testappli
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-gov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-gov-quotas
