apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-rbac
  namespace: argocd-rbac
spec:
  extraConfig:
    application.resourceTrackingMethod: annotation
    installationID: argocd-rbac
    oidc.config: |
      name: FreeIPA
      issuer: https://argocd-rbac-server-argocd-rbac.apps.ocp4-upi.skyr.dca.scc/api/dex
      clientID: argo-cd
      clientSecret: $oidc.dex.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      insecureSkipVerify: true
    resource.inclusions: |
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role","RoleBinding"]
      - apiGroups: [""]
        kinds: ["ServiceAccount"]
  namespaceManagement:
    - allowManagedBy: true
      name: testappli
  server:
    route:
      enabled: true
  sso:
    provider: dex
    dex:
      config: |
        logger:
          level: debug
        connectors:
        - type: ldap
          id: freeipa
          name: FreeIPA
          config:
            host: idm.skyr.dca.scc:636
            insecureNoSSL: false
            insecureSkipVerify: true
            bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            bindPW: Redhat2025!
            userSearch:
              baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=person)"
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: cn
            groupSearch:
              baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=groupOfNames)"
              userMatchers:
              - userAttr: dn
                groupAttr: member
              nameAttr: cn
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-dev
  namespace: argocd-dev
spec:
  extraConfig:
    application.resourceTrackingMethod: annotation
    installationID: argocd-dev
    oidc.config: |
      name: FreeIPA
      issuer: https://argocd-dev-server-argocd-dev.apps.ocp4-upi.skyr.dca.scc/api/dex
      clientID: argo-cd
      clientSecret: $oidc.dex.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      insecureSkipVerify: true
    resource.inclusions: |
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role","RoleBinding"]
      - apiGroups: [""]
        kinds: ["ServiceAccount","LimitRange","ResourceQuota","NetworkPolicy"]
  namespaceManagement:
    - allowManagedBy: true
      name: testappli
  server:
    route:
      enabled: true
  sso:
    provider: dex
    dex:
      config: |
        logger:
          level: debug
        connectors:
        - type: ldap
          id: freeipa
          name: FreeIPA
          config:
            host: idm.skyr.dca.scc:636
            insecureNoSSL: false
            insecureSkipVerify: true
            bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            bindPW: Redhat2025!
            userSearch:
              baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=person)"
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: cn
            groupSearch:
              baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=groupOfNames)"
              userMatchers:
              - userAttr: dn
                groupAttr: member
              nameAttr: cn
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-gov
  namespace: argocd-gov
spec:
  extraConfig:
    application.resourceTrackingMethod: annotation
    installationID: argocd-gov
    oidc.config: |
      name: FreeIPA
      issuer: https://argocd-gov-server-argocd-gov.apps.ocp4-upi.skyr.dca.scc/api/dex
      clientID: argo-cd
      clientSecret: $oidc.dex.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      insecureSkipVerify: true
    resource.inclusions: |
      - apiGroups: [""]
        kinds: ["ResourceQuota","LimitRange"]
  namespaceManagement:
    - allowManagedBy: true
      name: testappli
  server:
    route:
      enabled: true
  sso:
    provider: dex
    dex:
      config: |
        logger:
          level: debug
        connectors:
        - type: ldap
          id: freeipa
          name: FreeIPA
          config:
            host: idm.skyr.dca.scc:636
            insecureNoSSL: false
            insecureSkipVerify: true
            bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            bindPW: Redhat2025!
            userSearch:
              baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=person)"
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: cn
            groupSearch:
              baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
              filter: "(objectClass=groupOfNames)"
              userMatchers:
              - userAttr: dn
                groupAttr: member
              nameAttr: cn
