apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-rbac
  namespace: argocd-rbac
spec:
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-rbac"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: ["rbac.authorization.k8s.io"]
          kinds: ["Role","RoleBinding"]
        - apiGroups: [""]
          kinds: ["ServiceAccount"]
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-dev
  namespace: argocd-dev
spec:
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-dev"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: [""]
          kinds: ["Secret","ConfigMap","Service","PersistentVolumeClaim"]
        - apiGroups: ["apps"]
          kinds: ["Deployment","StatefulSet"]
        - apiGroups: ["route.openshift.io"]
          kinds: ["Route"]
      resource.exclusions: |
        - apiGroups: [""]
          kinds: ["ResourceQuota","LimitRange"]
        - apiGroups: ["rbac.authorization.k8s.io"]
          kinds: ["Role","RoleBinding","ClusterRole","ClusterRoleBinding"]
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-gov
  namespace: argocd-gov
spec:
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-gov"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: [""]
          kinds: ["ResourceQuota","LimitRange"]
      resource.exclusions: |
        - apiGroups: ["apps"]
          kinds: ["Deployment","StatefulSet","ReplicaSet"]
