apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-rbac
  namespace: argocd-rbac
spec:
  dex:
    config: |
      logger:
        level: debug
      connectors:
      - type: ldap
        id: freeipa
        name: FreeIPA
        config:
          host: idm.skyr.dca.scc:636
          insecureNoSSL: false
          insecureSkipVerify: false
          rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVqakNDQXZhZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEzTVJVd0V3WURWUVFLREF4VFMxbFMKTGtSRFFTNVRRME14SGpBY0JnTlZCQU1NRlVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVUQWVGdzB5TkRBeApNekF3T0RNM05EUmFGdzAwTkRBeE16QXdPRE0zTkRSYU1EY3hGVEFUQmdOVkJBb01ERk5MV1ZJdVJFTkJMbE5EClF6RWVNQndHQTFVRUF3d1ZRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TUlJQm9qQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBdVRxRmlUdEQ1aU1iejJzOEFDL2lzeW4reVRHMXZTNnMrY3R5MWZXLwpEWjNKQk9aS3Jid2VJVUg3Z1g3bVdnclZXTVdyK1NzL25yeHpWYytZbHo5Y1g0aS9uaUYzTFNKQmM0U3U5MU1lCi9MQ2JyOFFyeS82NjZzbW1TSGVEbGt5U0tJMEZITVNsL09XL1JXRmJ1NXhibmFlU0taWk5JU1NwcklxSGlMdzEKeUY0SjJscFB2a09zNW1ITlppT0wyY0QveVFqVGZjYlo2cmZ3SUNwRmZqTmJNTTdMdTFONUd5YUxidHNJTndKMAppaUhVUVlCN0R2OGkzM1ZTVTA3a1lGcFNDbEs3TXlIcEJ1Y1F6MzNGZVRheHpGTHNnYmpmaDV5RXJtOENjNldjCkJVQXFxbnIxNldKWFNnMFBzeVRiVmFGbmVsS0dZZHpSK00rTGVMOTYzTXVJMDFiUTNJUktOQ1JwWndWUlhMVlUKY0V4ZXdhR3NRbHNRWXcxQkNSOXNxWXByZnZaOWNPM0NwdG8vR0NrRnJiSGNwczQ0eFVLeU1qV251MmhQQXdUMQpGSW9ld3RCdGpiRHhNc2VWQlRRd0lEeU1MRXdpS2xmZHpjN3VDNlBEZVYzbTNwbUczVTJ3cTYzTWtQVGNzajRhCndTa2VZSDdCdDR6UXhEeFVpa0pWM2tDdEFnTUJBQUdqZ2FRd2dhRXdId1lEVlIwakJCZ3dGb0FVWUk0VTRlVzEKc2dST24vMGI0S1RIZlArY1Q4SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQWNZdwpIUVlEVlIwT0JCWUVGR0NPRk9IbHRiSUVUcC85RytDa3gzei9uRS9DTUQ0R0NDc0dBUVVGQndFQkJESXdNREF1CkJnZ3JCZ0VGQlFjd0FZWWlhSFIwY0RvdkwybHdZUzFqWVM1emEzbHlMbVJqWVM1elkyTXZZMkV2YjJOemNEQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBWXdQT0ZYOVpTbTY4Q2RCTFNKRURNOXdBVlRWMkV3SS8remhlcCtxcApTVHJLY0lrOHhUa0lVZUw2bEI3cUlBSXFwRjJ5azVMV3M0NlZqakZXdjhJa2pzOTEzamwwL3dCbjJjZmo2NDNLClJDZGRuNEQxV0NNZ0VadjVnVThhR1lpVEk3OTQzbTV5dm5rTVhyZHBTWXNLQnEzam4rajd6Q2JOV3NoWm1UaTcKSm5LOHZWSDNkL2VVZHpQM0lUSnU5dDVmMnJoRmppbjkxMUtLYzRPZDZJcUh1SmNIZWVqRTVsL2tiTktSRjNDWAo5UThuY0VSWW53OUM5eWZheUtFVVBsKzBUY3pOc29rK045bVh2UGJHMnhuWE91YytwT1Fndk9RdXFZWTFFT0QzCmNNYnR5aTFaQ1VpRXp3bEJCb3BXNElhay9ieVhIbzRCM3lUTklnRHVld0czL29LNXV6MFdCMjBXQjhUeXYxcTkKanF5SjVPMGNWaHlOKzhLYWZHbk14Tk1tTkVNd1pSc3NPMEI1dmc4b0NrVnQ1V0Q2R0NoQlpUZ0F4UG5kZElNbApWZFJFN2EwMFU1dFM2a1NwK05Nam9sTE5odFFpQTlMb25Ca2tYejNPSW8wd1ErMW8zOVhTbm5HdTNRYnc0aUZ5CndlSWRPTk9INXk1bXFMUFU0aU54WFcyVwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
          bindPW: Redhat2025!
          userSearch:
            baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=person)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=groupOfNames)"
            userMatchers:
            - userAttr: dn
              groupAttr: member
            nameAttr: cn
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-rbac"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: ["rbac.authorization.k8s.io"]
          kinds: ["Role","RoleBinding"]
        - apiGroups: [""]
          kinds: ["ServiceAccount"]
      oidc.config: |
        name: FreeIPA
        issuer: https://argocd-rbac-server-argocd-rbac.apps.ocp4-upi.skyr.dca.scc/api/dex
        clientID: argo-cd
        clientSecret: $oidc.dex.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJZUF4WGxGYzlGSVV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE56WTFPREV5TVZvWApEVEkzTVRJeE5URTFNekV5TWxvd0p6RWxNQ01HQTFVRUF3d2NLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1ClpHTmhMbk5qWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEpKZmlmTFc5NmoKU05BamE1TmVNVHpZVDZHOVk0NUtzM0Z4dnhNYnBSZUJLMkJXL1NkeEhrNSszNXRGQnMxY0V4bUROdk5hQVRydwplcmsxd0s1bmVTQ3U2bGpsQjdQZTZoc1RVOGJsWjNvRDB2V1RFY1puTWJYb0VhTVk5am1DNE9FSEt6cEJXdFZLCkJGZWI0VWx1OGZXRW5HTVpBcGMwU0FiQmExamVGNUhsc2d1TjNaNnVoSFllbldOTVNMbVhlc0w1YytNRkxscm0KdHVCcHZYTjQvWmw0TlVBR1E2N1JNWHF2My9ZS0JNbnFWeUJDNDJmV29wcTZXdHlxN2tGRVdsQXB2bzgxOU1PMgpUaEZtS2QyeS8wV3UxbTNNL0c4VVlyNTR1bitsQ0hWdWkyTGE1Y2cydytkMTNCcndTUXRHVDdGM3JuVEkvYUszClQzRUZOSmkxd0FNQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVENmc1S3ByZk11U1lSdlpaQXJIUgpXQ3FVWUs4d0h3WURWUjBqQkJnd0ZvQVUvdHRBWlg4TkpqTzB6UnJ1bVRwbUZjcFg1Z0V3SndZRFZSMFJCQ0F3CkhvSWNLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1WkdOaExuTmpZekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVV4WjRPRTAzZUhob053ejRNcG5YSUpPbUh3UTVQRVlST3ZXZUVFOTZ0TnBoelRwbGllQklHbzZzN3NmcQpCSldoOWJ2aDluZVF2WTJudUZWR3hoeEhVYmFwV0ZuQ1ZKanpBYkxOa0hIcUhRL0E1NmNiOUhmbW92THIvdlJlClJ4WlFCZXEyN1NjZElOQm83OHM1cmtmdHJqVzNqR0hhb0p1SXJ5cWhrMU44QmN5cjJORXRZSjdGYnlLWFhQT0QKQnVzNDRqY2N6bzkxYkhyM0ExUHkyU0h6eUlFSENxTE10UzRLRUhqZ0p5eVJxUzhkcU53ZmVNbFhWK1NSN0VoOQovelduN2c1YXROZVoyRThDaWtnNXdmeXB6UElUaHlKWVhNZldDVjZpTEU0UlYzREl0Q0ROZkQ4b2huZkV2SjRTClFTZlVmTVQrR0g0dzRvcENXY1JiU0N6aDZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-dev
  namespace: argocd-dev
spec:
  dex:
    config: |
      logger:
        level: debug
      connectors:
      - type: ldap
        id: freeipa
        name: FreeIPA
        config:
          host: idm.skyr.dca.scc:636
          insecureNoSSL: false
          insecureSkipVerify: false
          rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVqakNDQXZhZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEzTVJVd0V3WURWUVFLREF4VFMxbFMKTGtSRFFTNVRRME14SGpBY0JnTlZCQU1NRlVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVUQWVGdzB5TkRBeApNekF3T0RNM05EUmFGdzAwTkRBeE16QXdPRE0zTkRSYU1EY3hGVEFUQmdOVkJBb01ERk5MV1ZJdVJFTkJMbE5EClF6RWVNQndHQTFVRUF3d1ZRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TUlJQm9qQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBdVRxRmlUdEQ1aU1iejJzOEFDL2lzeW4reVRHMXZTNnMrY3R5MWZXLwpEWjNKQk9aS3Jid2VJVUg3Z1g3bVdnclZXTVdyK1NzL25yeHpWYytZbHo5Y1g0aS9uaUYzTFNKQmM0U3U5MU1lCi9MQ2JyOFFyeS82NjZzbW1TSGVEbGt5U0tJMEZITVNsL09XL1JXRmJ1NXhibmFlU0taWk5JU1NwcklxSGlMdzEKeUY0SjJscFB2a09zNW1ITlppT0wyY0QveVFqVGZjYlo2cmZ3SUNwRmZqTmJNTTdMdTFONUd5YUxidHNJTndKMAppaUhVUVlCN0R2OGkzM1ZTVTA3a1lGcFNDbEs3TXlIcEJ1Y1F6MzNGZVRheHpGTHNnYmpmaDV5RXJtOENjNldjCkJVQXFxbnIxNldKWFNnMFBzeVRiVmFGbmVsS0dZZHpSK00rTGVMOTYzTXVJMDFiUTNJUktOQ1JwWndWUlhMVlUKY0V4ZXdhR3NRbHNRWXcxQkNSOXNxWXByZnZaOWNPM0NwdG8vR0NrRnJiSGNwczQ0eFVLeU1qV251MmhQQXdUMQpGSW9ld3RCdGpiRHhNc2VWQlRRd0lEeU1MRXdpS2xmZHpjN3VDNlBEZVYzbTNwbUczVTJ3cTYzTWtQVGNzajRhCndTa2VZSDdCdDR6UXhEeFVpa0pWM2tDdEFnTUJBQUdqZ2FRd2dhRXdId1lEVlIwakJCZ3dGb0FVWUk0VTRlVzEKc2dST24vMGI0S1RIZlArY1Q4SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQWNZdwpIUVlEVlIwT0JCWUVGR0NPRk9IbHRiSUVUcC85RytDa3gzei9uRS9DTUQ0R0NDc0dBUVVGQndFQkJESXdNREF1CkJnZ3JCZ0VGQlFjd0FZWWlhSFIwY0RvdkwybHdZUzFqWVM1emEzbHlMbVJqWVM1elkyTXZZMkV2YjJOemNEQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBWXdQT0ZYOVpTbTY4Q2RCTFNKRURNOXdBVlRWMkV3SS8remhlcCtxcApTVHJLY0lrOHhUa0lVZUw2bEI3cUlBSXFwRjJ5azVMV3M0NlZqakZXdjhJa2pzOTEzamwwL3dCbjJjZmo2NDNLClJDZGRuNEQxV0NNZ0VadjVnVThhR1lpVEk3OTQzbTV5dm5rTVhyZHBTWXNLQnEzam4rajd6Q2JOV3NoWm1UaTcKSm5LOHZWSDNkL2VVZHpQM0lUSnU5dDVmMnJoRmppbjkxMUtLYzRPZDZJcUh1SmNIZWVqRTVsL2tiTktSRjNDWAo5UThuY0VSWW53OUM5eWZheUtFVVBsKzBUY3pOc29rK045bVh2UGJHMnhuWE91YytwT1Fndk9RdXFZWTFFT0QzCmNNYnR5aTFaQ1VpRXp3bEJCb3BXNElhay9ieVhIbzRCM3lUTklnRHVld0czL29LNXV6MFdCMjBXQjhUeXYxcTkKanF5SjVPMGNWaHlOKzhLYWZHbk14Tk1tTkVNd1pSc3NPMEI1dmc4b0NrVnQ1V0Q2R0NoQlpUZ0F4UG5kZElNbApWZFJFN2EwMFU1dFM2a1NwK05Nam9sTE5odFFpQTlMb25Ca2tYejNPSW8wd1ErMW8zOVhTbm5HdTNRYnc0aUZ5CndlSWRPTk9INXk1bXFMUFU0aU54WFcyVwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
          bindPW: Redhat2025!
          userSearch:
            baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=person)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=groupOfNames)"
            userMatchers:
            - userAttr: dn
              groupAttr: member
            nameAttr: cn
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-dev"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: [""]
          kinds: ["Secret","ConfigMap","Service","PersistentVolumeClaim"]
        - apiGroups: ["apps"]
          kinds: ["Deployment","StatefulSet"]
        - apiGroups: ["route.openshift.io"]
          kinds: ["Route"]
      oidc.config: |
        name: FreeIPA
        issuer: https://argocd-dev-server-argocd-dev.apps.ocp4-upi.skyr.dca.scc/api/dex
        clientID: argo-cd
        clientSecret: $oidc.dex.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJZUF4WGxGYzlGSVV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE56WTFPREV5TVZvWApEVEkzTVRJeE5URTFNekV5TWxvd0p6RWxNQ01HQTFVRUF3d2NLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1ClpHTmhMbk5qWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEpKZmlmTFc5NmoKU05BamE1TmVNVHpZVDZHOVk0NUtzM0Z4dnhNYnBSZUJLMkJXL1NkeEhrNSszNXRGQnMxY0V4bUROdk5hQVRydwplcmsxd0s1bmVTQ3U2bGpsQjdQZTZoc1RVOGJsWjNvRDB2V1RFY1puTWJYb0VhTVk5am1DNE9FSEt6cEJXdFZLCkJGZWI0VWx1OGZXRW5HTVpBcGMwU0FiQmExamVGNUhsc2d1TjNaNnVoSFllbldOTVNMbVhlc0w1YytNRkxscm0KdHVCcHZYTjQvWmw0TlVBR1E2N1JNWHF2My9ZS0JNbnFWeUJDNDJmV29wcTZXdHlxN2tGRVdsQXB2bzgxOU1PMgpUaEZtS2QyeS8wV3UxbTNNL0c4VVlyNTR1bitsQ0hWdWkyTGE1Y2cydytkMTNCcndTUXRHVDdGM3JuVEkvYUszClQzRUZOSmkxd0FNQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVENmc1S3ByZk11U1lSdlpaQXJIUgpXQ3FVWUs4d0h3WURWUjBqQkJnd0ZvQVUvdHRBWlg4TkpqTzB6UnJ1bVRwbUZjcFg1Z0V3SndZRFZSMFJCQ0F3CkhvSWNLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1WkdOaExuTmpZekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVV4WjRPRTAzZUhob053ejRNcG5YSUpPbUh3UTVQRVlST3ZXZUVFOTZ0TnBoelRwbGllQklHbzZzN3NmcQpCSldoOWJ2aDluZVF2WTJudUZWR3hoeEhVYmFwV0ZuQ1ZKanpBYkxOa0hIcUhRL0E1NmNiOUhmbW92THIvdlJlClJ4WlFCZXEyN1NjZElOQm83OHM1cmtmdHJqVzNqR0hhb0p1SXJ5cWhrMU44QmN5cjJORXRZSjdGYnlLWFhQT0QKQnVzNDRqY2N6bzkxYkhyM0ExUHkyU0h6eUlFSENxTE10UzRLRUhqZ0p5eVJxUzhkcU53ZmVNbFhWK1NSN0VoOQovelduN2c1YXROZVoyRThDaWtnNXdmeXB6UElUaHlKWVhNZldDVjZpTEU0UlYzREl0Q0ROZkQ4b2huZkV2SjRTClFTZlVmTVQrR0g0dzRvcENXY1JiU0N6aDZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      resource.exclusions: |
        - apiGroups: [""]
          kinds: ["ResourceQuota","LimitRange"]
        - apiGroups: ["rbac.authorization.k8s.io"]
          kinds: ["Role","RoleBinding","ClusterRole","ClusterRoleBinding"]
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-gov
  namespace: argocd-gov
spec:
  dex:
    config: |
      logger:
        level: debug
      connectors:
      - type: ldap
        id: freeipa
        name: FreeIPA
        config:
          host: idm.skyr.dca.scc:636
          insecureNoSSL: false
          insecureSkipVerify: false
          rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVqakNDQXZhZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEzTVJVd0V3WURWUVFLREF4VFMxbFMKTGtSRFFTNVRRME14SGpBY0JnTlZCQU1NRlVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVUQWVGdzB5TkRBeApNekF3T0RNM05EUmFGdzAwTkRBeE16QXdPRE0zTkRSYU1EY3hGVEFUQmdOVkJBb01ERk5MV1ZJdVJFTkJMbE5EClF6RWVNQndHQTFVRUF3d1ZRMlZ5ZEdsbWFXTmhkR1VnUVhWMGFHOXlhWFI1TUlJQm9qQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBdVRxRmlUdEQ1aU1iejJzOEFDL2lzeW4reVRHMXZTNnMrY3R5MWZXLwpEWjNKQk9aS3Jid2VJVUg3Z1g3bVdnclZXTVdyK1NzL25yeHpWYytZbHo5Y1g0aS9uaUYzTFNKQmM0U3U5MU1lCi9MQ2JyOFFyeS82NjZzbW1TSGVEbGt5U0tJMEZITVNsL09XL1JXRmJ1NXhibmFlU0taWk5JU1NwcklxSGlMdzEKeUY0SjJscFB2a09zNW1ITlppT0wyY0QveVFqVGZjYlo2cmZ3SUNwRmZqTmJNTTdMdTFONUd5YUxidHNJTndKMAppaUhVUVlCN0R2OGkzM1ZTVTA3a1lGcFNDbEs3TXlIcEJ1Y1F6MzNGZVRheHpGTHNnYmpmaDV5RXJtOENjNldjCkJVQXFxbnIxNldKWFNnMFBzeVRiVmFGbmVsS0dZZHpSK00rTGVMOTYzTXVJMDFiUTNJUktOQ1JwWndWUlhMVlUKY0V4ZXdhR3NRbHNRWXcxQkNSOXNxWXByZnZaOWNPM0NwdG8vR0NrRnJiSGNwczQ0eFVLeU1qV251MmhQQXdUMQpGSW9ld3RCdGpiRHhNc2VWQlRRd0lEeU1MRXdpS2xmZHpjN3VDNlBEZVYzbTNwbUczVTJ3cTYzTWtQVGNzajRhCndTa2VZSDdCdDR6UXhEeFVpa0pWM2tDdEFnTUJBQUdqZ2FRd2dhRXdId1lEVlIwakJCZ3dGb0FVWUk0VTRlVzEKc2dST24vMGI0S1RIZlArY1Q4SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQWNZdwpIUVlEVlIwT0JCWUVGR0NPRk9IbHRiSUVUcC85RytDa3gzei9uRS9DTUQ0R0NDc0dBUVVGQndFQkJESXdNREF1CkJnZ3JCZ0VGQlFjd0FZWWlhSFIwY0RvdkwybHdZUzFqWVM1emEzbHlMbVJqWVM1elkyTXZZMkV2YjJOemNEQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBWXdQT0ZYOVpTbTY4Q2RCTFNKRURNOXdBVlRWMkV3SS8remhlcCtxcApTVHJLY0lrOHhUa0lVZUw2bEI3cUlBSXFwRjJ5azVMV3M0NlZqakZXdjhJa2pzOTEzamwwL3dCbjJjZmo2NDNLClJDZGRuNEQxV0NNZ0VadjVnVThhR1lpVEk3OTQzbTV5dm5rTVhyZHBTWXNLQnEzam4rajd6Q2JOV3NoWm1UaTcKSm5LOHZWSDNkL2VVZHpQM0lUSnU5dDVmMnJoRmppbjkxMUtLYzRPZDZJcUh1SmNIZWVqRTVsL2tiTktSRjNDWAo5UThuY0VSWW53OUM5eWZheUtFVVBsKzBUY3pOc29rK045bVh2UGJHMnhuWE91YytwT1Fndk9RdXFZWTFFT0QzCmNNYnR5aTFaQ1VpRXp3bEJCb3BXNElhay9ieVhIbzRCM3lUTklnRHVld0czL29LNXV6MFdCMjBXQjhUeXYxcTkKanF5SjVPMGNWaHlOKzhLYWZHbk14Tk1tTkVNd1pSc3NPMEI1dmc4b0NrVnQ1V0Q2R0NoQlpUZ0F4UG5kZElNbApWZFJFN2EwMFU1dFM2a1NwK05Nam9sTE5odFFpQTlMb25Ca2tYejNPSW8wd1ErMW8zOVhTbm5HdTNRYnc0aUZ5CndlSWRPTk9INXk1bXFMUFU0aU54WFcyVwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
          bindDN: uid=openshift,cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
          bindPW: Redhat2025!
          userSearch:
            baseDN: cn=users,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=person)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=skyr,dc=dca,dc=scc
            filter: "(objectClass=groupOfNames)"
            userMatchers:
            - userAttr: dn
              groupAttr: member
            nameAttr: cn
  server:
    route:
      enabled: true
  extraConfig:
    argocd-cm: |
      installationID: "argocd-gov"
      application.resourceTrackingMethod: annotation
      resource.inclusions: |
        - apiGroups: [""]
          kinds: ["ResourceQuota","LimitRange"]
      oidc.config: |
        name: FreeIPA
        issuer: https://argocd-gov-server-argocd-gov.apps.ocp4-upi.skyr.dca.scc/api/dex
        clientID: argo-cd
        clientSecret: $oidc.dex.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
        rootCAData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiekNDQWxlZ0F3SUJBZ0lJZUF4WGxGYzlGSVV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE56WTFPREV5TVZvWApEVEkzTVRJeE5URTFNekV5TWxvd0p6RWxNQ01HQTFVRUF3d2NLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1ClpHTmhMbk5qWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUEpKZmlmTFc5NmoKU05BamE1TmVNVHpZVDZHOVk0NUtzM0Z4dnhNYnBSZUJLMkJXL1NkeEhrNSszNXRGQnMxY0V4bUROdk5hQVRydwplcmsxd0s1bmVTQ3U2bGpsQjdQZTZoc1RVOGJsWjNvRDB2V1RFY1puTWJYb0VhTVk5am1DNE9FSEt6cEJXdFZLCkJGZWI0VWx1OGZXRW5HTVpBcGMwU0FiQmExamVGNUhsc2d1TjNaNnVoSFllbldOTVNMbVhlc0w1YytNRkxscm0KdHVCcHZYTjQvWmw0TlVBR1E2N1JNWHF2My9ZS0JNbnFWeUJDNDJmV29wcTZXdHlxN2tGRVdsQXB2bzgxOU1PMgpUaEZtS2QyeS8wV3UxbTNNL0c4VVlyNTR1bitsQ0hWdWkyTGE1Y2cydytkMTNCcndTUXRHVDdGM3JuVEkvYUszClQzRUZOSmkxd0FNQ0F3RUFBYU9CbnpDQm5EQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVENmc1S3ByZk11U1lSdlpaQXJIUgpXQ3FVWUs4d0h3WURWUjBqQkJnd0ZvQVUvdHRBWlg4TkpqTzB6UnJ1bVRwbUZjcFg1Z0V3SndZRFZSMFJCQ0F3CkhvSWNLaTVoY0hCekxtOWpjRFF0ZFhCcExuTnJlWEl1WkdOaExuTmpZekFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVV4WjRPRTAzZUhob053ejRNcG5YSUpPbUh3UTVQRVlST3ZXZUVFOTZ0TnBoelRwbGllQklHbzZzN3NmcQpCSldoOWJ2aDluZVF2WTJudUZWR3hoeEhVYmFwV0ZuQ1ZKanpBYkxOa0hIcUhRL0E1NmNiOUhmbW92THIvdlJlClJ4WlFCZXEyN1NjZElOQm83OHM1cmtmdHJqVzNqR0hhb0p1SXJ5cWhrMU44QmN5cjJORXRZSjdGYnlLWFhQT0QKQnVzNDRqY2N6bzkxYkhyM0ExUHkyU0h6eUlFSENxTE10UzRLRUhqZ0p5eVJxUzhkcU53ZmVNbFhWK1NSN0VoOQovelduN2c1YXROZVoyRThDaWtnNXdmeXB6UElUaHlKWVhNZldDVjZpTEU0UlYzREl0Q0ROZkQ4b2huZkV2SjRTClFTZlVmTVQrR0g0dzRvcENXY1JiU0N6aDZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      resource.exclusions: |
        - apiGroups: ["apps"]
          kinds: ["Deployment","StatefulSet","ReplicaSet"]
