apiVersion: v1
kind: Secret
metadata:
  name: repo-credentials
  namespace: argocd-rbac
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://bastion.skyr.dca.scc:3000/demoscc/OCP_GITOPS.git
  username: "skyr"
  password: "Redhat2025!"
  # Plus de "insecure: true" car nous avons le certificat ci-dessous
  # tlsClientConfig.caData: |
  #   -----BEGIN CERTIFICATE-----
  #   MIIEjjCCAvagAwIBAgIBATANBgkqhkiG9w0BAQsFADA3MRUwEwYDVQQKDAxTS1lS
  #   LkRDQS5TQ0MxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNDAx
  #   MzAwODM3NDRaFw00NDAxMzAwODM3NDRaMDcxFTATBgNVBAoMDFNLWVIuRENBLlND
  #   QzEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0B
  #   AQEFAAOCAY8AMIIBigKCAYEAuTqFiTtD5iMbz2s8AC/isyn+yTG1vS6s+cty1fW/
  #   DZ3JBOZKrbweIUH7gX7mWgrVWMWr+Ss/nrxzVc+Ylz9cX4i/niF3LSJBc4Su91Me
  #   /LCbr8Qry/666smmSHeDlkySKI0FHMSl/OW/RWFbu5xbnaeSKZZNISSprIqHiLw1
  #   yF4J2lpPvkOs5mHNZiOL2cD/yQjTfcbZ6rfwICpFfjNbMM7Lu1N5GyaLbtsINwJ0
  #   iiHUQYB7Dv8i33VSU07kYFpSClK7MyHpBucQz33FeTaxzFLsgbjfh5yErm8Cc6Wc
  #   BUAqqnr16WJXSg0PsyTbVaFnelKGYdzR+M+LeL963MuI01bQ3IRKNCRpZwVRXLVU
  #   cExewaGsQlsQYw1BCR9sqYprfvZ9cO3Cpto/GCkFrbHcps44xUKyMjWnu2hPAwT1
  #   FIoewtBtjbDxMseVBTQwIDyMLEwiKlfdzc7uC6PDeV3m3pmG3U2wq63MkPTcsj4a
  #   wSkeYH7Bt4zQxDxUikJV3kCtAgMBAAGjgaQwgaEwHwYDVR0jBBgwFoAUYI4U4eW1
  #   sgROn/0b4KTHfP+cT8IwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYw
    # HQYDVR0OBBYEFGCOFOHltbIETp/9G+Ckx3z/nE/CMD4GCCsGAQUFBwEBBDIwMDAu
    # BggrBgEFBQcwAYYiaHR0cDovL2lwYS1jYS5za3lyLmRjYS5zY2MvY2Evb2NzcDAN
    # BgkqhkiG9w0BAQsFAAOCAYEAYwPOFX9ZSm68CdBLSJEDM9wAVTV2EwI/+zhep+qp
    # STrKcIk8xTkIUeL6lB7qIAIqpF2yk5LWs46VjjFWv8Ikjs913jl0/wBn2cfj643K
    # RCddn4D1WCMgEZv5gU8aGYiTI7943m5yvnkMXrdpSYsKBq3jn+j7zCbNWshZmTi7
    # JnK8vVH3d/eUdzP3ITJu9t5f2rhFjin911KKc4Od6IqHuJcHeejE5l/kbNKRF3CX
    # 9Q8ncERYnw9C9yfayKEUPl+0TczNsok+N9mXvPbG2xnXOuc+pOQgvOQuqYY1EOD3
    # cMbtyi1ZCUiEzwlBBopW4Iak/byXHo4B3yTNIgDuewG3/oK5uz0WB20WB8Tyv1q9
    # jqyJ5O0cVhyN+8KafGnMxNMmNEMwZRssO0B5vg8oCkVt5WD6GChBZTgAxPnddIMl
    # VdRE7a00U5tS6kSp+NMjolLNhtQiA9LonBkkXz3OIo0wQ+1o39XSnnGu3Qbw4iFy
    # weIdONOH5y5mqLPU4iNxXW2W
    # -----END CERTIFICATE-----
  insecure: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-credentials
  namespace: argocd-dev
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://bastion.skyr.dca.scc:3000/demoscc/OCP_GITOPS.git
  username: "skyr"
  password: "Redhat2025!"
  # tlsClientConfig.caData: |
  #   -----BEGIN CERTIFICATE-----
  #   MIIEjjCCAvagAwIBAgIBATANBgkqhkiG9w0BAQsFADA3MRUwEwYDVQQKDAxTS1lS
  #   LkRDQS5TQ0MxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNDAx
  #   MzAwODM3NDRaFw00NDAxMzAwODM3NDRaMDcxFTATBgNVBAoMDFNLWVIuRENBLlND
  #   QzEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0B
  #   AQEFAAOCAY8AMIIBigKCAYEAuTqFiTtD5iMbz2s8AC/isyn+yTG1vS6s+cty1fW/
  #   DZ3JBOZKrbweIUH7gX7mWgrVWMWr+Ss/nrxzVc+Ylz9cX4i/niF3LSJBc4Su91Me
  #   /LCbr8Qry/666smmSHeDlkySKI0FHMSl/OW/RWFbu5xbnaeSKZZNISSprIqHiLw1
  #   yF4J2lpPvkOs5mHNZiOL2cD/yQjTfcbZ6rfwICpFfjNbMM7Lu1N5GyaLbtsINwJ0
  #   iiHUQYB7Dv8i33VSU07kYFpSClK7MyHpBucQz33FeTaxzFLsgbjfh5yErm8Cc6Wc
  #   BUAqqnr16WJXSg0PsyTbVaFnelKGYdzR+M+LeL963MuI01bQ3IRKNCRpZwVRXLVU
  #   cExewaGsQlsQYw1BCR9sqYprfvZ9cO3Cpto/GCkFrbHcps44xUKyMjWnu2hPAwT1
  #   FIoewtBtjbDxMseVBTQwIDyMLEwiKlfdzc7uC6PDeV3m3pmG3U2wq63MkPTcsj4a
  #   wSkeYH7Bt4zQxDxUikJV3kCtAgMBAAGjgaQwgaEwHwYDVR0jBBgwFoAUYI4U4eW1
  #   sgROn/0b4KTHfP+cT8IwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYw
    # HQYDVR0OBBYEFGCOFOHltbIETp/9G+Ckx3z/nE/CMD4GCCsGAQUFBwEBBDIwMDAu
    # BggrBgEFBQcwAYYiaHR0cDovL2lwYS1jYS5za3lyLmRjYS5zY2MvY2Evb2NzcDAN
    # BgkqhkiG9w0BAQsFAAOCAYEAYwPOFX9ZSm68CdBLSJEDM9wAVTV2EwI/+zhep+qp
    # STrKcIk8xTkIUeL6lB7qIAIqpF2yk5LWs46VjjFWv8Ikjs913jl0/wBn2cfj643K
    # RCddn4D1WCMgEZv5gU8aGYiTI7943m5yvnkMXrdpSYsKBq3jn+j7zCbNWshZmTi7
    # JnK8vVH3d/eUdzP3ITJu9t5f2rhFjin911KKc4Od6IqHuJcHeejE5l/kbNKRF3CX
    # 9Q8ncERYnw9C9yfayKEUPl+0TczNsok+N9mXvPbG2xnXOuc+pOQgvOQuqYY1EOD3
    # cMbtyi1ZCUiEzwlBBopW4Iak/byXHo4B3yTNIgDuewG3/oK5uz0WB20WB8Tyv1q9
    # jqyJ5O0cVhyN+8KafGnMxNMmNEMwZRssO0B5vg8oCkVt5WD6GChBZTgAxPnddIMl
    # VdRE7a00U5tS6kSp+NMjolLNhtQiA9LonBkkXz3OIo0wQ+1o39XSnnGu3Qbw4iFy
    # weIdONOH5y5mqLPU4iNxXW2W
    # -----END CERTIFICATE-----
  insecure: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-credentials
  namespace: argocd-gov
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://bastion.skyr.dca.scc:3000/demoscc/OCP_GITOPS.git
  username: "skyr"
  password: "Redhat2025!"
  # tlsClientConfig.caData: |
  #   -----BEGIN CERTIFICATE-----
  #   MIIEjjCCAvagAwIBAgIBATANBgkqhkiG9w0BAQsFADA3MRUwEwYDVQQKDAxTS1lS
  #   LkRDQS5TQ0MxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yNDAx
  #   MzAwODM3NDRaFw00NDAxMzAwODM3NDRaMDcxFTATBgNVBAoMDFNLWVIuRENBLlND
  #   QzEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0B
  #   AQEFAAOCAY8AMIIBigKCAYEAuTqFiTtD5iMbz2s8AC/isyn+yTG1vS6s+cty1fW/
  #   DZ3JBOZKrbweIUH7gX7mWgrVWMWr+Ss/nrxzVc+Ylz9cX4i/niF3LSJBc4Su91Me
  #   /LCbr8Qry/666smmSHeDlkySKI0FHMSl/OW/RWFbu5xbnaeSKZZNISSprIqHiLw1
  #   yF4J2lpPvkOs5mHNZiOL2cD/yQjTfcbZ6rfwICpFfjNbMM7Lu1N5GyaLbtsINwJ0
  #   iiHUQYB7Dv8i33VSU07kYFpSClK7MyHpBucQz33FeTaxzFLsgbjfh5yErm8Cc6Wc
  #   BUAqqnr16WJXSg0PsyTbVaFnelKGYdzR+M+LeL963MuI01bQ3IRKNCRpZwVRXLVU
  #   cExewaGsQlsQYw1BCR9sqYprfvZ9cO3Cpto/GCkFrbHcps44xUKyMjWnu2hPAwT1
  #   FIoewtBtjbDxMseVBTQwIDyMLEwiKlfdzc7uC6PDeV3m3pmG3U2wq63MkPTcsj4a
  #   wSkeYH7Bt4zQxDxUikJV3kCtAgMBAAGjgaQwgaEwHwYDVR0jBBgwFoAUYI4U4eW1
  #   sgROn/0b4KTHfP+cT8IwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYw
    # HQYDVR0OBBYEFGCOFOHltbIETp/9G+Ckx3z/nE/CMD4GCCsGAQUFBwEBBDIwMDAu
    # BggrBgEFBQcwAYYiaHR0cDovL2lwYS1jYS5za3lyLmRjYS5zY2MvY2Evb2NzcDAN
    # BgkqhkiG9w0BAQsFAAOCAYEAYwPOFX9ZSm68CdBLSJEDM9wAVTV2EwI/+zhep+qp
    # STrKcIk8xTkIUeL6lB7qIAIqpF2yk5LWs46VjjFWv8Ikjs913jl0/wBn2cfj643K
    # RCddn4D1WCMgEZv5gU8aGYiTI7943m5yvnkMXrdpSYsKBq3jn+j7zCbNWshZmTi7
    # JnK8vVH3d/eUdzP3ITJu9t5f2rhFjin911KKc4Od6IqHuJcHeejE5l/kbNKRF3CX
    # 9Q8ncERYnw9C9yfayKEUPl+0TczNsok+N9mXvPbG2xnXOuc+pOQgvOQuqYY1EOD3
    # cMbtyi1ZCUiEzwlBBopW4Iak/byXHo4B3yTNIgDuewG3/oK5uz0WB20WB8Tyv1q9
    # jqyJ5O0cVhyN+8KafGnMxNMmNEMwZRssO0B5vg8oCkVt5WD6GChBZTgAxPnddIMl
    # VdRE7a00U5tS6kSp+NMjolLNhtQiA9LonBkkXz3OIo0wQ+1o39XSnnGu3Qbw4iFy
    # weIdONOH5y5mqLPU4iNxXW2W
    # -----END CERTIFICATE-----
  insecure: "true"
