apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: argocd-sync
  namespace: gitops-demo
spec:
  params:
    - name: ARGOCD_SERVER
      type: string
      default: argocd-server.openshift-gitops.svc.cluster.local:443
    - name: ARGOCD_APP
      type: string
      default: customer-stack
    - name: ARGOCD_TOKEN
      type: string
  steps:
    - name: sync
      image: registry.redhat.io/openshift4/argocd-rhel8:v2.13
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        export ARGOCD_OPTS="--grpc-web"
        argocd login $(params.ARGOCD_SERVER) --auth-token $(params.ARGOCD_TOKEN) --insecure
        argocd app sync $(params.ARGOCD_APP)
        argocd app wait $(params.ARGOCD_APP) --sync --health
