apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-gov-quotas
  namespace: testappli
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["resourcequotas","limitranges"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-gov-quotas
  namespace: testappli
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-gov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-gov-quotas
