apiVersion: batch/v1
kind: Job
metadata:
  name: seed-customers
  namespace: gitops-demo
  labels:
    app.kubernetes.io/name: seed-customers
    app.kubernetes.io/part-of: ocp-gitops-demo
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seed-customers
        app.kubernetes.io/part-of: ocp-gitops-demo
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: harbor.skyr.dca.scc/gitops/customer-db-init:0.1.0
          env:
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: customers
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
