apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-namespace-access-demoscc
  namespace: openshift-gitops
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
