apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-project-admin-demoscc
  namespace: openshift-gitops
subjects:
  - kind: User
    name: demoscc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-project-admin
