apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-project-admin
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "appprojects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
